# collect-pre-update-data defaults


#: dict of str: Executable modes with class names from mods directory.
#: Keys must match mode module name.
MODES_INTERNAL_MAP = {
    "default":           "ModeDefault",
    "mods_reporter":     "ModeModsReporter",
    "check_patches_f":   "ModeCheckPatchesF",
    "patches_inventory": "ModePatchesInventory",
    "network":           "ModeNetwork",
    "hardware":          "ModeHardware",
    "sender":            "ModeSender"
}

#: dict of str: Executable modes with class names from mods directory.
#: Keys must match mode name and values are names from above dict.
MODES_USER_MAP = {
    "default":           "default",
    "mods-reporter":     "mods_reporter",
    "check-patches-f":   "check_patches_f",
    "patches-inventory": "patches_inventory",
    "network-auto":      "network",
    "network-check":     "network",
    "network-backup":    "network",
    "hardware":          "hardware",
    "sender":            "sender"
}


#: str: Path to the root directory for script logs and collected data.
DATA_DIR = "/porta_var/update/collect_pre_update_data"

#: str: Path to directory for temporary files such as thread buffers.
TMP_DIR = "/porta_var/tmp/collect_pre_update_data"


#: str: Path to the check_patches_f directory where it stores data.
PCUP_BACKUP_DIR = "/porta_var/update/backup"

#: str: Path to the remote shell wrapper PC utility.
RSH_WRAPPER = "/home/porta-configurator/bin/rsh-wrapper.sh"


#: str: Path to the Patches Inventory home directory where
#: all code is stored.
PI_APPDIR = "/porta_var/.pi/app"

#: str: Path to the Patches Inventory executable.
PI_APPBIN = f"{PI_APPDIR}/bin/pi.sh"


#TODO: on available resources:
# 1. Review regexes and separate Cloud expected changes into separate
#    list that also should be checked. It also requires to store in
#    Server fact whether it's Cloud or not. We can retrieve this fact
#    from CFG DB, fetching servers list from it instead of PI.


#: list of str: Regexes of OS paths that are always expected
#: to change and can safely be ignored.
EXPECTED_OS_CHANGES_IGNORED = [
    # str: Always dynamic or expected.
    r"^/etc/\.passphrases$",
    r"^/etc/docker/key\.json$",
    r"^/etc/grub\.conf$",
    r"^/etc/iproute2/rt_tables$",
    r"^/etc/os-release\.porta$",
    r"^/etc/porta-one/corosync/cluster-nodes\.conf\.removed_[^/]+$",
    r"^/etc/porta-one/web/web-vip-[^/]+.conf$",
    r"^/etc/ssh/moduli$",
    r"^/etc/sysconfig/iptables(\.save)?$",
    r"^/etc/system-release\.porta$",
    r"^/etc/tuned/(active_profile|profile_mode)$",
    # str: Autogenerated.
    r"^/etc/\.updated$",
    r"^/etc/audit/audit\.rules$",
    r"^/etc/authselect/\S+$",
    r"^/etc/pam\.d/system-auth-ac$",
    r"^/etc/sysconfig/ipset\.d/\.saved$",
    # str: Covered by NetworkProcessor.
    r"^/etc/NetworkManager/system-connections/[^/]+.nmconnection$",
    r"^/etc/sysconfig/network$",
    r"^/etc/sysconfig/network-scripts/(rule|ifcfg|route)-[^/]+$",
    # str: Don't care.
    r"^/etc/X11/\S+$",
    r"^/etc/alternatives/(lib64|percona)$",
    r"^/etc/alternatives/if(down|up)$",
    r"^/etc/favicon\.png$",
    r"^/etc/fonts/conf\.d/\S$",
    r"^/etc/gitconfig$",
    r"^/etc/kernel/install\.d/\S+$",
    r"^/etc/lvm/backup/\S+$",
    r"^/etc/porta-billing/\.git/\S+$",
    r"^/etc/prelink\.conf\.d/grub2\.conf$",
    r"^/etc/rc\.d/(init\.d|rc\d[^/]+)/\S+$",
    r"^/etc/sysconfig/ip_route_backup$",
    r"^/etc/sysconfig/ip_route_nm$",
    r"^/etc/sysconfig/network-scripts(_bkp|_?backup)([^/]+)?/\S+$",
    # str: I wonder why check_patches_f doesn't skip this.
    r"^/etc/hostname$",
    r"^/etc/localtime$",
    # str: I wonder why etckeeper tracks this.
    r"^/etc/g?shadow-?$",
    r"^/etc/group-?$",
    r"^/etc/passwd-?$",
    r"^/etc/sub[gu]id-?$",
    # str: Keys/certs often mentioned and always skipped.
    r"^/etc/pki/tls/(certs|private)/(exim\.pem|localhost\.(crt|key))$",
    r"^/etc/ssh/ssh_host_[^/]+_key[^/]*$",
    # str: Likely belongs to known RPMs.
    r"^/etc/logrotate\.d/pacemaker$",
    r"^/etc/logrotate\.d/pcsd$",
    r"^/etc/pam\.d/pcsd$",
    r"^/etc/pki/nssdb/(cert9|key4).db$",
    r"^/etc/sysconfig/network-scripts/if(up|down)(-[^/]+)?$",
    r"^/etc/systemd/system/(basic|multi-user)\.target\.wants/iptables\.service$",
    r"^/etc/systemd/system/multi-user\.target\.wants/NetworkManager(-wait-online)?\.service$",
    r"^/etc/systemd/system/network-online\.target\.wants/NetworkManager(-wait-online)?\.service$",
    r"^/etc/systemd/system/dbus-org\.freedesktop\.nm-dispatcher\.service$",
    # str: Managed by PC.
    r"^/etc/NetworkManager/conf\.d/99-custom-plugins.conf$",
    r"^/etc/corosync/corosync\.(conf[^/]+|xml)$",
    r"^/etc/cron\.d/(archivist|porta-configurator)$",
    r"^/etc/cron\.d/archivist/archivist/\S+$",
    r"^/etc/fail2ban/\S+$",
    r"^/etc/httpd/conf/custom-repository\.httpd\.conf$",
    r"^/etc/opensearch/index-templates/cdrmediator_[^/]+.json$",
    r"^/etc/porta-one/common/maintenance\.conf$",
    r"^/etc/porta-one/corosync/vip-based-configs\.list$",
    r"^/etc/porta-one/diaconv/auth(user|group)$",
    r"^/etc/redis-sentinel\.conf$",
    r"^/etc/supervisord\.d/psmsc-periodic-tasks-[^/]+.conf$",
    r"^/etc/sysconfig/ipset\.d/((mub|db|cqt)fw-[^/]+|sip-cluster-\d+-[^/]+|f2b-sshd).set",
    r"^/etc/sysconfig/radiusd$",
    r"^/etc/systemd/system/cdr-extd-all\.target\.wants/cdr-extd@cdr-extraction-[^/]+\.service$",
    r"^/etc/systemd/system/cdr-ratingd-all\.target\.wants/cdr-ratingd@cdr-rating-[^/]+\.service$",
    r"^/etc/systemd/system/custom_sync_cgroup_swappiness\.service$",
    r"^/etc/systemd/system/multi-user\.target\.wants/cdr-extd@cdr-extraction-[^/]+\.service$",
    r"^/etc/systemd/system/multi-user\.target\.wants/cdr-ratingd@cdr-rating-[^/]+\.service$",
    r"^/etc/systemd/system/multi-user\.target\.wants/custom_sync_cgroup_swappiness\.service$",
    r"^/etc/systemd/system/multi-user\.target\.wants/logmaster-(sipcluster|psfs)@[^/]+\.service$",
    r"^/etc/systemd/system/sockets\.target\.wants/tftp\.socket$",
    r"^/usr/lib/prince/license/license\.dat$",
    # str: Most likely managed by MON.
    r"^/etc/nagios/objects/(services|templates)\.cfg\.(bak|new)$",
    r"^/etc/porta-one/appstream/changelog/porta-monitor(-options)?$",
    r"^/etc/systemd/system/multi-user\.target\.wants/nsca\.service$",
    # str: OCI stuff.
    r"^/etc/porta-one/cloud/\S+$",
    r"^/etc/systemd/system/oci-network\.service$",
    # str: Rarely really modified.
    r"^/etc/fstab$",
    r"^/etc/selinux/config$",
]

#: list of str: Regexes of OS paths that are expected to change
#: but the user should be warned.
EXPECTED_OS_CHANGES_WARNING = [
    # str: Cloud change but crucial for non-cloud installations.
    r"^/etc/multipath/bindings$",
    r"^/etc/multipath\.conf(\.bak)?$",
    r"^/etc/systemd/system/multi-user\.target\.wants/iscsid\.service$",
    r"^/etc/systemd/system/sockets\.target\.wants/multipathd\.socket$",
    r"^/etc/systemd/system/sysinit\.target\.wants/multipathd\.service$",
    # str: Custom prompts/MOHs/etc.
    r"^/var/lib/porta-sip/sounds/\S+$",
    r"^/var/lib/psmsc/prompts/\S+$",
    # str: Definitely patched/changed from our side.
    r"^/etc/nagios/nagios\.cfg$",
    r"^/usr/bin/edgeproxy$",
    r"^/usr/bin/imgate$",
    r"^/usr/bin/python-porta$",
    r"^/usr/bin/rtpproxy$",
    r"^/usr/bin/sip-forwarder$",
    r"^/usr/lib/systemd/system/mu-bundle@\.service$",
    r"^/usr/sbin/nscasender$",
    # str: Often changes, but crucial.
    r"^/etc/chrony\.conf$",
    r"^/etc/multipath/wwids$",
    r"^/etc/ssh/sshd?_config$",
    r"^/etc/sysconfig/grub$",
    r"^/etc/sysctl\.conf$",
    r"^/etc/yum.repos\.d/new\.repo$",
]

#: list of str: Regexes of Git controlled paths that are always expected
#: to change and can safely be ignored.
EXPECTED_REPO_CHANGES_IGNORED = [
    #: str: Always dynamic.
    r"^/home/porta-one/\.ssh/authorized_keys2$",
    #: str: Recompiled, if so PI bundle for dev package is present.
    r"^/home/porta-admin/apache/(new)?ui/dist/\S+$",
    #: str: Repos themselves.
    r"^/home/archivist/\.git(/\S+)?$",
    r"^/home/oracle/.git/\S+$",
    r"^/home/porta-(configurator|admin|one|billing|db|cdrmediator|um)/\.git/\S+$",
    r"^/home/porta-admin/apache/IPCentrex_SelfCare/.git/\S+$",
    r"^/home/porta-admin/apache/ui/\.git/\S+$",
    r"^/home/porta-configurator/data/\.git/\S+$",
    r"^/home/porta-sip/sippy/\.git/\S+$",
    r"^/home/porta-monitor/options/\.git/\S+$",
    r"^/home/provisioning-framework/.git/\S+$",
    r"^/usr/libexec/nagios/portaone/.git/\S+$",
    #: str: Various components for testing or just removed by RPM.
    r"^/home/porta-admin/(f?t(ests)?|_internal)/\S+$",
    r"^/home/porta-admin/apache/ui/ui_tests/\S+$",
    r"^/home/porta-admin/captive_portal/(README.md|client/\S+)$",
    r"^/home/porta-configurator/data/etc/options-dump/\S+$",
    r"^/home/porta-sip/(sippy/)?test/\S+$",
    r"^/usr/share/suitability-checker/portatest.py$",
]

#: list of str: Regexes of Git controlled paths that are always expected
#: to change but the user should be warned.
EXPECTED_REPO_CHANGES_WARNING = [
]

#: list of str: Regexes of RPMs expected in check_patches_f output
#: and should be ignored.
EXPECTED_INSTALLED_RPMS_IGNORED = [
    r"^(ModemManager|libappstream|json)-glib$",
    r"^(abattis-cantarell|(adobe-)source-code-pro)-fonts$",
    r"^(at-spi2-)?(atk)$",
    r"^(audit|xz|tcp_wrappers|systemd|rpm|bz2)-libs$",
    r"^(gcc-)?gdb(-plugin)?$",
    r"^(lib)?udisks2$",
    r"^.+-(cursor|icon)-theme$",
    r"^.+-debug(info|source)$",
    r"^OpenIPMI(-libs)?$",
    r"^aardvark-dns$",
    r"^apr-util-(bdb|openssl)$",
    r"^at-spi2-(core)$",
    r"^avahi(-.+)?$",
    r"^bubblewrap$",
    r"^buildah$",
    r"^cifs-.+$",
    r"^cloud-init$",
    r"^cloud-tools$",
    r"^clufter-bin$",
    r"^clufter-common$",
    r"^colord-libs$",
    r"^composefs-libs$",
    r"^conmon$",
    r"^containers-common(-extra)?$",
    r"^cracklib$",
    r"^criu(-libs)?$",
    r"^crun$",
    r"^cups-(ipptool|libs)$",
    r"^cx_Oracle$",
    r"^cyrus-sasl-lib$",
    r"^dbus-(tools|libs)$",
    r"^dconf$",
    r"^docker-(buildx-plugin|ce-rootless-extras)$",
    r"^efi-filesystem$",
    r"^efibootmgr$",
    r"^efivar-libs$",
    r"^elfutils-(libs|libelf)$",
    r"^exempi$",
    r"^exiv2(-libs)?$",
    r"^expat$",
    r"^fdk-aac-free$",
    r"^flatpak(-(selinux|session-helper))?$",
    r"^fuse(3|3?-(overlayfs|common|libs))?$",
    r"^fwupd(-plugin-flashrom)?$",
    r"^gawk-all-langpacks$",
    r"^gdisk$",
    r"^gdk-pixbuf2-modules$",
    r"^geoclue2$",
    r"^geolite2-(city|country)$",
    r"^giflib$",
    r"^glib-networking$",
    r"^glib2$",
    r"^gnupg2-smime$",
    r"^graphene$",
    r"^grub2-(pc(-modules)?|tools-(extra|minimal)?|efi-x64)$",
    r"^grubby-deprecated$",
    r"^gsettings-desktop-schemas$",
    r"^gstreamer1(-plugins-base)?$",
    r"^gtk-.+$",
    r"^gtk[23]$",
    r"^hardlink$",
    r"^httpd$",
    r"^ipmitool$",
    r"^iso-codes$",
    r"^iwlax2xx-firmware$",
    r"^jack-audio-connection-kit$",
    r"^kernel$",
    r"^libX(11-xcb|cursor|damage|inerama|randr|v|xf86vm)$",
    r"^lib[lt]db$",
    r"^libacl$",
    r"^libatasmart$",
    r"^libattr$",
    r"^libblkid$",
    r"^libblockdev$",
    r"^libblockdev-?(crypto|fs|loop|mdraid|part|swap|utils)$",
    r"^libbytesize$",
    r"^libcanberra(-gtk[23])?$",
    r"^libcap(-ng(-python3)?)?$",
    r"^libdb$",
    r"^libepoxy$",
    r"^libexif$",
    r"^libffi$",
    r"^libgcrypt$",
    r"^libgexiv2$",
    r"^libglvnd(-(egl|glx))?$",
    r"^libgpg-error$",
    r"^libgsf$",
    r"^libgudev$",
    r"^libgxps$",
    r"^libiptcdata$",
    r"^libknet1-(compress|crypto)?-[^-]+-plugin$",
    r"^libknet1-(compress|crypto)?-plugins-all$",
    r"^libldac$",
    r"^libmount$",
    r"^libnet$",
    r"^libnotify$",
    r"^libnozzle1$",
    r"^libosinfo$",
    r"^libproxy(-webkitgtk4)?$",
    r"^libsbc$",
    r"^libsecret$",
    r"^libslirp$",
    r"^libsoup$",
    r"^libstemmer$",
    r"^libtevent$",
    r"^libtraceevent$",
    r"^libtracker-sparql$",
    r"^liburing$",
    r"^libuuid$",
    r"^libwayland(-.+)?$",
    r"^libwbclient$",
    r"^libxkbcommon$",
    r"^libxshmfence$",
    r"^lm_sensors-libs$",
    r"^lmdb-libs$",
    r"^low-memory-monitor$",
    r"^lua$",
    r"^memstrack$",
    r"^mesa(-.+)?$",
    r"^mod_(http2|lua)$",
    r"^ncurses-libs$",
    r"^netavark$",
    r"^network-scripts(-team)?$",
    r"^nodejs-(docs|full-i18n)$",
    r"^npm$",
    r"^nspr$",
    r"^nss(-(util|softokn))?$",
    r"^oddjob-mkhomedir$",
    r"^open-vm-tools$",
    r"^openldap$",
    r"^openssh-(clients|server)$",
    r"^openssl-pkcs11$",
    r"^oracle-cloud-agent$",
    r"^orc$",
    r"^os-prober$",
    r"^osinfo(-db(-tools)?)?$",
    r"^ostree-libs$",
    r"^p11-kit-server$",
    r"^pacemaker-schemas$",
    r"^pam$",
    r"^passt(-selinux)?$",
    r"^pcs$",
    r"^perl-(HTTP-Daemon|PSGI|XML-Filter-BufferText|Barcode-Code128|CPAN-DistnameInfo)$",
    r"^perl-(Term-Size-(Any|Perl)|Clone|MIME-Charset|Unicode-LineBreak|NDBM_File|bignum)$",
    r"^perl-(doc|libs|Test-.+)$",
    r"^php-(fpm|opcache)$",
    r"^pinentry$",
    r"^pipewire(-.+)?$",
    r"^pjproject$",
    r"^pmm[23]?-(client|server)$",
    r"^podman$",
    r"^polkit-pkla-compat$",
    r"^poppler(-(data|glib))?$",
    r"^popt$",
    r"^portaone-logos$",
    r"^portaudio$",
    r"^python2-(pip|setuptools|PyMySQL)$",
    r"^python3-(json(patch|pointer|schema)|jwt|oauthlib|prettytable|prompt-toolkit|pygments)$",
    r"^python3-(pexpect|ptyprocess|magic|clufter|pycurl|unbound|arrow|certificonfigobj|jmespath)$",
    r"^python3-(terminaltables|wcwidth|importlib-metadata|zipp|perf|file-magic)$",
    r"^python3-(unversioned-command)$",
    r"^python36-(circuitbreaker|oci-cli|oci-sdk|net-snmp)$",
    r"^qpress$",
    r"^rpm-plugin-systemd-inhibit$",
    r"^rsyslog-logrotate$",
    r"^rtkit$",
    r"^ruby-(default-gems|irb)$",
    r"^rubygem-(bigdecimal|did_you_mean|io-console|json|rdoc|bundler)$",
    r"^samba-(libs|(common|client)(-(tools|libs))?)$",
    r"^shadow-utils-subid$",
    r"^slirp4netns$",
    r"^sombok$",
    r"^sound-theme-.+$",
    r"^sqlite$",
    r"^storcli$",
    r"^timedatex$",
    r"^totem-pl-parser$",
    r"^tracker(-miners)?$",
    r"^trousers(-lib)?$",
    r"^upower$",
    r"^webkit2gtk3-jsc$",
    r"^wireplumber(-.+)?$",
    r"^xdg-(desktop-.+|dbus-proxy)$",
    r"^xkeyboard-config$",
    r"^yajl$",
]

#: list of str: Regexes of RPMs expected in check_patches_f output
#: but user should be warned.
EXPECTED_INSTALLED_RPMS_WARNING = [
]


#: dict of str: Regexes for check_patches_f output parsing. Used for
#: both matching and capturing. Key names are tied to the
#: PCModsParser lifecycle. DON'T CHANGE KEYS OR REMOVE ANY REGEX
#: UNLESS YOU KNOW WHAT YOU ARE DOING!
CHECK_PATCHES_F_REGEX_MAP = {

    #: str: Just a blank line.
    "blank": r"^\s*$",

    #: str: "----- sip1 192.168.0.107 -----".
    "server_header": r"^-{3,5} (?P<name>\S+) (?P<ip>\S+) -{3,5}$",

    #: str: "Modified /etc config files:".
    "modified_etc_header": r"^Modified /etc config files:$",

    #: str: "  /etc/.updated".
    "modified_etc_file": r"^  (?P<path>/etc/\S+)$",

    #: str: "Modified files:".
    "modified_rpm_header": r"^Modified files:$",

    #: str: "  porta-configurator-data".
    "modified_rpm_name": r"^  (?P<name>\S+)$",

    #: str: "      Unsatisfied dependencies for porta-selfcare-115.4-1.20250124.1.el8.noarch:".
    "unsatisfied_deps_header": r"^ {6}Unsatisfied dependencies for \S+:$",

    #: str: "      SM5..UGT.    /home/porta-configurator/data/options/webcluster.def",
    #: or "      S.5....T.    /usr/libexec/nagios/portaone/gearman.pl".
    "modified_rpm_file": r"^ {6}(?:[\w.]{9}|missing) ? ? {4}(?P<path>/\S+)$",

    #: str: "Missing rpms: ci-provision."
    "missing_rpms": r"^Missing rpms:.+$",

    #: str: "Check installed rpms:".
    "check_installed_rpms_header": r"^Check installed rpms:$",

    #: str: Any line that is not check_installed_rpms_dont_install.
    "check_installed_rpms_flood": r"^\[debug\] (?!Shouldn't be installed:).*$",

    #: str: "[info] rpms in custom-delete group: ['audit-libs', 'avahi-libs',...]"
    "check_installed_rpms_custom_delete": r"\[(debug|info)\] rpms in custom-delete group: \[(?P<rpms>[^\]]+)\]",

    #: str: "[debug] Shouldn't be installed: pcs-0.10.17-2.0.1.el8.x86_64".
    "check_installed_rpms_dont_install": r"^\[(debug|info)\] Shouldn't be installed: (?P<rpm>\S*)$",

    #: str: "tt.local config files:".
    "tt_local_header": r"^tt.local config files:$",

    #: str: "    /home/porta-configurator/etc/tt/shared/exim.conf.tt.local".
    "tt_local_file": r"^ {4}(?P<path>/\S+)$",

    #: str: "Custom httpd conf file was found: /etc/httpd/conf.d/porta.httpd.777679.conf".
    "custom_httpd_conf": r"^Custom httpd conf file was found: (?P<path>/etc/httpd/\S+)$",

    #: str: "All custom patched files are backed up to".
    "archives": r"^All custom patched files are backed up to$"
}

#: str: Regex to extract RPM name without version.
RPM_NAME = r"^(?P<name>.+?)(-\d[^-]*(-[^-.]+(?:\.[^.]+)*)?)?$"

#: str: Regex to detect customer patches in PI.
PI_SLURP_SUBJECT_PREFIX_CSP = r"^(CUSTOM CHANGE on|CUSTOMER CHANGES):.+$"


#: list of str: Patches Inventory summary module fields to retrieve in
#: expected order. DON'T CHANGE WITHOUT UNDERSTANDING!
PI_SUMMARY_FIELDS_ORDER = [
    "bundle_sha_short",
    "bundle_shortname",
    "is_dirty",
    "is_staged",
    "patch_sha_short",
    "patch_subj",
    "patch_number",
    "change",
    "file_w_pkgdir",
    "csup_tt",
    "dev_tt",
    "fixed_in",
    "servers_full"
]

#: list of str: Patches Inventory summary fields not required for the
#: parsing process. NB this doesn't mean they don't impact reporting!
PI_SUMMARY_NOT_MANDATORY_FIELDS = [
    "patch_subj",
    "csup_tt",
    "dev_tt",
    "fixed_in"
]


#: str: Regex to check ticket from CLI args.
CSUP_TT_REGEX = "^PortaOne-[0-9]{3,5}$"

#: dict of str or int: Default email parameters for sender mode.
SENDER_MAIL_PARAMS = {
    #: str: Target host to send the email with zipped backup.
    "smtp_host": "smtp-in.portaone.com",
    #: int: Port on the target host to send the backup to.
    "smtp_port": 25,
    #: str: Value for the From header.
    "mail_from": "task_int@portaone.com",
    #: str: Value for the To header (production).
    #"mail_to":   "csup-youtrack@portaone.com",
    #: str: Value for the To header (staging).
    "mail_to":   "csup-youtrack-dev@portaone.com"
}

#: bool: Adds cookie to attachements. Cookie is the following string:
#: (example is multline but real string is oneliner)
#:      \n
#:      CPUD_COOKIE;
#:      backup_id:<backup_id>;
#:      start_epoch:<start_epoch>;
#:      attach_src:<path_to_original_file>;
#:      attach_md5:<md5_sum_of_original_file>;
#:      attach_time:<epoch_as_float_rounded_to_3>;
#: Cookie might be required to bypass YT duplicate attachements filter.
SENDER_SUPPLY_COOKIE = True

#: int: Max attachement size in megabytes. If exceeded then tries to zip
#: the affected file. If still exceed then fails.
SENDER_MAX_ATTACHEMENT_SIZE = 512


#: str: Symbol used in modifications report to visually separate blocks.
REPORT_SEPARATOR_SYMBOL = "="
#: int: Desired lenght of separator used in modifications report.
REPORT_SEPARATOR_WIDTH = 100


#: str: Name of class that defines how progressbar looks.
#: For more details refer to libs.progressbar.
PROGRESSBAR_STYLE_MAIN = "ProgressbarStyleLarge7s5h4d3"

#: str: Name of class that defines how progressbar looks.
#: Used in case if main style doesn't fit in terminal sizes.
PROGRESSBAR_STYLE_FALLBACK = "ProgressbarStyleCompact7s5h4d3"

#: float: Seconds interval to change progressbar on screen.
PROGRESSBAR_SWAP_INTERVAL = 0.25

#: int: Defines minimum required space for dependent (dynamic) elements
#: of progressbar. In case of lack of space it's rendering is considered
#: impossible and simply event name will be shown.
PROGRESSBAR_MIN_SPACING = 5

#: int: Defines minimum content that should left after cutting adaptive
#: elements of progressbar. Cutting is performed in case of size limits.
PROGRESSBAR_MIN_CUT_CONTENT = 10

#: int: Defines maximum render attempt allowed before falling back
#: to compact progressbar.
PROGRESSBAR_MAX_RENDER_ATTEMPTS = 3

#: int: Number of components waiting for possibility to draw something
#: to terminal which triggers progressbars to give them such.
PROGRESSBAR_WAITERS_THRESHOLD = 1


#: int: Seconds interval for heartbeat that reminds user about
#: currently running events registered by components.
HEARTBEAT_INTERVAL = 60

#: dict of str: Hooks IDs and their class names that enable components
#: tracking for places known to be too silent from users' point of view.
#: Some of the below trackers might imply too verbosive behavior in logs.
EVENTS_HOOKS_MAP = {

    #: str: Enables logic for tracking PC check_patches_f collection.
    #: Recommended for regular usage.
    "pc_output_collection":      "PCModsParserOutputCollectionHook",

    #: str: Enables logic for tracking PI summary collection.
    #: Recommended for regular usage.
    "pi_output_collection":      "PIModsParserOutputCollectionHook",

    #: str: Enables logic for tracking PC mods processing in reporting.
    #: Recommended for regular usage.
    "report_pcms_processing":    "ModsReporterPCModsProcessingHook",

    #: str: Enables logic for tracking child processes issued
    #: by PCModsParser._resolve_files_rpms(),
    #: i.e., when suite identifies modified files owner RPMs.
    "pc_owner_rpms_resolution":  "PCModsParserRPMsResolvingHook",

    #: str: Enables logic for tracing cases when suite collects
    #: by ModsReporter._run_cmd_on_pcm_affected_for_report(),
    #: i.e., when suite collects modified files diffs for full report.
    #"report_details_collection": "ModsReporterDetailsCollectionHook",

    #: str: Enables logic for tracking each submode enter and exit.
    "submode_general":           "SubmodeGeneralHook",

    #: str: DON'T EVEN THINK TO USE THIS IN PRODUCTION!
    #: Traces literally every Server().run_cmd() execution.
    #"every_server_cmd":          "ServerRunCmdEveryHook",

    #: str: DON'T EVEN THINK TO USE THIS IN PRODUCTION!
    #: Traces almost every PopenWrapper() invocation.
    #"every_child":               "PopenWrapperEveryHook"
}


#: str: Default date format for logs.
DATE_FORMAT = "%Y-%m-%dT%H:%M:%S"

#: str: Default log message format.
LOG_FORMAT = (
    "%(asctime)s.%(msecs)03dZ "
    "[%(levelname).1s] "
    "[%(process)d.%(thread)d] "
    "/%(name)s/ "
    "%(message)s"
)

#: str: Debug log message format.
LOG_FORMAT_DEBUG = (
    "%(asctime)s.%(msecs)03dZ "
    "[%(levelname).1s] "
    "[%(process)d.%(thread)d] "
    "/%(name)s/%(funcName)s:%(lineno)d/ "
    " %(message)s"
)

#: int: Numeric log level for USER, should be between WARNING
#: and ERROR to show informative but crucial information to user.
USER_LEVEL = 37

